version: "3"

services:
  frontend:
    build: ./solution-6
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_URL='http://127.0.0.1:3001/'
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "3001:3001"